# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import printing_pb2 as printing__pb2


class PrintingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendToPrinter = channel.unary_unary(
                '/distributed_printing.PrintingService/SendToPrinter',
                request_serializer=printing__pb2.PrintRequest.SerializeToString,
                response_deserializer=printing__pb2.PrintResponse.FromString,
                )


class PrintingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendToPrinter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrintingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendToPrinter': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToPrinter,
                    request_deserializer=printing__pb2.PrintRequest.FromString,
                    response_serializer=printing__pb2.PrintResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_printing.PrintingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrintingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendToPrinter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed_printing.PrintingService/SendToPrinter',
            printing__pb2.PrintRequest.SerializeToString,
            printing__pb2.PrintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MutualExclusionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/distributed_printing.MutualExclusionService/RequestAccess',
                request_serializer=printing__pb2.AccessRequest.SerializeToString,
                response_deserializer=printing__pb2.AccessResponse.FromString,
                )
        self.ReleaseAccess = channel.unary_unary(
                '/distributed_printing.MutualExclusionService/ReleaseAccess',
                request_serializer=printing__pb2.AccessRelease.SerializeToString,
                response_deserializer=printing__pb2.Empty.FromString,
                )


class MutualExclusionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutualExclusionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=printing__pb2.AccessRequest.FromString,
                    response_serializer=printing__pb2.AccessResponse.SerializeToString,
            ),
            'ReleaseAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseAccess,
                    request_deserializer=printing__pb2.AccessRelease.FromString,
                    response_serializer=printing__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_printing.MutualExclusionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MutualExclusionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed_printing.MutualExclusionService/RequestAccess',
            printing__pb2.AccessRequest.SerializeToString,
            printing__pb2.AccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed_printing.MutualExclusionService/ReleaseAccess',
            printing__pb2.AccessRelease.SerializeToString,
            printing__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
