# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: printing.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprinting.proto\x12\x14\x64istributed_printing\"m\n\x0cPrintRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x17\n\x0fmessage_content\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\x12\x16\n\x0erequest_number\x18\x04 \x01(\x05\"Y\n\rPrintResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x14\x63onfirmation_message\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\"U\n\rAccessRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\x12\x16\n\x0erequest_number\x18\x03 \x01(\x05\"C\n\x0e\x41\x63\x63\x65ssResponse\x12\x16\n\x0e\x61\x63\x63\x65ss_granted\x18\x01 \x01(\x08\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\"U\n\rAccessRelease\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\x12\x16\n\x0erequest_number\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2k\n\x0fPrintingService\x12X\n\rSendToPrinter\x12\".distributed_printing.PrintRequest\x1a#.distributed_printing.PrintResponse2\xc7\x01\n\x16MutualExclusionService\x12Z\n\rRequestAccess\x12#.distributed_printing.AccessRequest\x1a$.distributed_printing.AccessResponse\x12Q\n\rReleaseAccess\x12#.distributed_printing.AccessRelease\x1a\x1b.distributed_printing.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'printing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRINTREQUEST']._serialized_start=40
  _globals['_PRINTREQUEST']._serialized_end=149
  _globals['_PRINTRESPONSE']._serialized_start=151
  _globals['_PRINTRESPONSE']._serialized_end=240
  _globals['_ACCESSREQUEST']._serialized_start=242
  _globals['_ACCESSREQUEST']._serialized_end=327
  _globals['_ACCESSRESPONSE']._serialized_start=329
  _globals['_ACCESSRESPONSE']._serialized_end=396
  _globals['_ACCESSRELEASE']._serialized_start=398
  _globals['_ACCESSRELEASE']._serialized_end=483
  _globals['_EMPTY']._serialized_start=485
  _globals['_EMPTY']._serialized_end=492
  _globals['_PRINTINGSERVICE']._serialized_start=494
  _globals['_PRINTINGSERVICE']._serialized_end=601
  _globals['_MUTUALEXCLUSIONSERVICE']._serialized_start=604
  _globals['_MUTUALEXCLUSIONSERVICE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
